### ISSUE TITLE
deps are using outdated format

### ISSUE THREAD

**Issue by andykais** [dmitriytat/keypress#3]
installing your module results in this error:
```
Download https://deno.land/std@v0.55.0/encoding/utf8.ts
Warning std versions prefixed with 'v' were deprecated recently. Please change your import to https://deno.land/std@0.55.0/encoding/utf8.ts (at https://deno.land/std@v0.55.0/encoding/utf8.ts)
error: Import 'https://deno.land/std@v0.55.0/encoding/utf8.ts' failed: 404 Not Found
    at https://deno.land/x/keypress@0.0.4/dep.ts:1:0
```
I see that it is using the new version format on your master branch. Versions do not get overridden in deno though, I believe you just need to release a `0.0.5` version of the library

**Comment by dmitriytat** [comment]
I have just realised 0.0.7 version and it successfully updated in deno.land.

**Comment by andykais** [comment]
thank you!
